# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb=_b('\n\rmessage.proto\"\x17\n\x08PingTest\x12\x0b\n\x03num\x18\x01 \x02(\r\"r\n\x0ePinModeControl\x12\x0b\n\x03pin\x18\x01 \x02(\r\x12\"\n\x04mode\x18\x02 \x02(\x0e\x32\x14.PinModeControl.Mode\"/\n\x04Mode\x12\t\n\x05INPUT\x10\x00\x12\n\n\x06OUTPUT\x10\x01\x12\x10\n\x0cINPUT_PULLUP\x10\x02\"\xa7\x01\n\x0bIOReadWrite\x12\x0b\n\x03pin\x18\x01 \x02(\r\x12)\n\toperation\x18\x02 \x02(\x0e\x32\x16.IOReadWrite.Operation\x12\x0b\n\x03val\x18\x03 \x01(\r\"S\n\tOperation\x12\x10\n\x0c\x44IGITAL_READ\x10\x00\x12\x11\n\rDIGITAL_WRITE\x10\x01\x12\x0f\n\x0b\x41NALOG_READ\x10\x02\x12\x10\n\x0c\x41NALOG_WRITE\x10\x03\"\x8e\x01\n\x0cServoControl\x12\x0b\n\x03pin\x18\x01 \x02(\r\x12*\n\toperation\x18\x02 \x02(\x0e\x32\x17.ServoControl.Operation\x12\x0b\n\x03val\x18\x03 \x01(\r\"8\n\tOperation\x12\n\n\x06\x41TTACH\x10\x00\x12\n\n\x06\x44\x45TACH\x10\x01\x12\t\n\x05WRITE\x10\x02\x12\x08\n\x04READ\x10\x03\"\xdd\x01\n\x07Message\x12\x1e\n\tping_test\x18\x01 \x01(\x0b\x32\t.PingTestH\x00\x12+\n\x10pin_mode_control\x18\x02 \x01(\x0b\x32\x0f.PinModeControlH\x00\x12%\n\rio_read_write\x18\x03 \x01(\x0b\x32\x0c.IOReadWriteH\x00\x12&\n\rservo_control\x18\x04 \x01(\x0b\x32\r.ServoControlH\x00\x12\x16\n\x0cthis_address\x18\x05 \x01(\rH\x00\x12\x17\n\rsystem_uptime\x18\x06 \x01(\rH\x00\x42\x05\n\x03msg')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PINMODECONTROL_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='PinModeControl.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INPUT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INPUT_PULLUP', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=109,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_PINMODECONTROL_MODE)

_IOREADWRITE_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='IOReadWrite.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_READ', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIGITAL_WRITE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANALOG_READ', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANALOG_WRITE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=243,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_IOREADWRITE_OPERATION)

_SERVOCONTROL_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='ServoControl.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ATTACH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DETACH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=415,
  serialized_end=471,
)
_sym_db.RegisterEnumDescriptor(_SERVOCONTROL_OPERATION)


_PINGTEST = _descriptor.Descriptor(
  name='PingTest',
  full_name='PingTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='PingTest.num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)


_PINMODECONTROL = _descriptor.Descriptor(
  name='PinModeControl',
  full_name='PinModeControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='PinModeControl.pin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='PinModeControl.mode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PINMODECONTROL_MODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=156,
)


_IOREADWRITE = _descriptor.Descriptor(
  name='IOReadWrite',
  full_name='IOReadWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='IOReadWrite.pin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='IOReadWrite.operation', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='IOReadWrite.val', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IOREADWRITE_OPERATION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=326,
)


_SERVOCONTROL = _descriptor.Descriptor(
  name='ServoControl',
  full_name='ServoControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='ServoControl.pin', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='ServoControl.operation', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='ServoControl.val', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVOCONTROL_OPERATION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=471,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping_test', full_name='Message.ping_test', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pin_mode_control', full_name='Message.pin_mode_control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='io_read_write', full_name='Message.io_read_write', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='servo_control', full_name='Message.servo_control', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='this_address', full_name='Message.this_address', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_uptime', full_name='Message.system_uptime', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='Message.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=474,
  serialized_end=695,
)

_PINMODECONTROL.fields_by_name['mode'].enum_type = _PINMODECONTROL_MODE
_PINMODECONTROL_MODE.containing_type = _PINMODECONTROL
_IOREADWRITE.fields_by_name['operation'].enum_type = _IOREADWRITE_OPERATION
_IOREADWRITE_OPERATION.containing_type = _IOREADWRITE
_SERVOCONTROL.fields_by_name['operation'].enum_type = _SERVOCONTROL_OPERATION
_SERVOCONTROL_OPERATION.containing_type = _SERVOCONTROL
_MESSAGE.fields_by_name['ping_test'].message_type = _PINGTEST
_MESSAGE.fields_by_name['pin_mode_control'].message_type = _PINMODECONTROL
_MESSAGE.fields_by_name['io_read_write'].message_type = _IOREADWRITE
_MESSAGE.fields_by_name['servo_control'].message_type = _SERVOCONTROL
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['ping_test'])
_MESSAGE.fields_by_name['ping_test'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['pin_mode_control'])
_MESSAGE.fields_by_name['pin_mode_control'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['io_read_write'])
_MESSAGE.fields_by_name['io_read_write'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['servo_control'])
_MESSAGE.fields_by_name['servo_control'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['this_address'])
_MESSAGE.fields_by_name['this_address'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['system_uptime'])
_MESSAGE.fields_by_name['system_uptime'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['PingTest'] = _PINGTEST
DESCRIPTOR.message_types_by_name['PinModeControl'] = _PINMODECONTROL
DESCRIPTOR.message_types_by_name['IOReadWrite'] = _IOREADWRITE
DESCRIPTOR.message_types_by_name['ServoControl'] = _SERVOCONTROL
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

PingTest = _reflection.GeneratedProtocolMessageType('PingTest', (_message.Message,), dict(
  DESCRIPTOR = _PINGTEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:PingTest)
  ))
_sym_db.RegisterMessage(PingTest)

PinModeControl = _reflection.GeneratedProtocolMessageType('PinModeControl', (_message.Message,), dict(
  DESCRIPTOR = _PINMODECONTROL,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:PinModeControl)
  ))
_sym_db.RegisterMessage(PinModeControl)

IOReadWrite = _reflection.GeneratedProtocolMessageType('IOReadWrite', (_message.Message,), dict(
  DESCRIPTOR = _IOREADWRITE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:IOReadWrite)
  ))
_sym_db.RegisterMessage(IOReadWrite)

ServoControl = _reflection.GeneratedProtocolMessageType('ServoControl', (_message.Message,), dict(
  DESCRIPTOR = _SERVOCONTROL,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ServoControl)
  ))
_sym_db.RegisterMessage(ServoControl)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
