/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Mon Jan  2 20:14:33 2017. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PingTest_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PingTest, num, num, 0),
    PB_LAST_FIELD
};

const pb_field_t PinModeControl_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PinModeControl, pin, pin, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, PinModeControl, mode, pin, 0),
    PB_LAST_FIELD
};

const pb_field_t IOReadWrite_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, IOReadWrite, pin, pin, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, IOReadWrite, operation, pin, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, IOReadWrite, val, operation, 0),
    PB_LAST_FIELD
};

const pb_field_t ServoControl_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, ServoControl, pin, pin, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, ServoControl, operation, pin, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, ServoControl, val, operation, 0),
    PB_LAST_FIELD
};

const pb_field_t Message_fields[7] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, Message, ping_test, ping_test, &PingTest_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , UNION, Message, pin_mode_control, pin_mode_control, &PinModeControl_fields),
    PB_ONEOF_FIELD(msg,   3, MESSAGE , ONEOF, STATIC  , UNION, Message, io_read_write, io_read_write, &IOReadWrite_fields),
    PB_ONEOF_FIELD(msg,   4, MESSAGE , ONEOF, STATIC  , UNION, Message, servo_control, servo_control, &ServoControl_fields),
    PB_ONEOF_FIELD(msg,   5, UINT32  , ONEOF, STATIC  , UNION, Message, this_address, this_address, 0),
    PB_ONEOF_FIELD(msg,   6, UINT32  , ONEOF, STATIC  , UNION, Message, system_uptime, system_uptime, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, msg.ping_test) < 65536 && pb_membersize(Message, msg.pin_mode_control) < 65536 && pb_membersize(Message, msg.io_read_write) < 65536 && pb_membersize(Message, msg.servo_control) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PingTest_PinModeControl_IOReadWrite_ServoControl_Message)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, msg.ping_test) < 256 && pb_membersize(Message, msg.pin_mode_control) < 256 && pb_membersize(Message, msg.io_read_write) < 256 && pb_membersize(Message, msg.servo_control) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PingTest_PinModeControl_IOReadWrite_ServoControl_Message)
#endif


/* @@protoc_insertion_point(eof) */
